/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author strattec
 */
package csmsquared.main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ChronoTimerGUI extends javax.swing.JFrame {
    /**
     * Creates new form ChronoTimerGUI
     */
    public ChronoTimerGUI() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	this.setTitle("Chrono Timer");
        titleLabel = new javax.swing.JLabel();
        addPlayerLbl = new javax.swing.JLabel();
        addPlayerText = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        racersQueueText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        activityMonitorText = new javax.swing.JTextArea();
        racersQueueLbl = new javax.swing.JLabel();
        activityMonitorLbl = new javax.swing.JLabel();
        raceTypeCB = new javax.swing.JComboBox();
        raceTpeLbl = new javax.swing.JLabel();
        startbtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        newRaceBtn = new javax.swing.JButton();
        endRace = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        titleLabel.setText("ChronoTimer");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addPlayerLbl.setText("Add Player : ");
        addPlayerText.setText("Enter ID");
        addBtn.setText("ADD");
        racersQueueText.setColumns(20);
        racersQueueText.setRows(5);
        jScrollPane1.setViewportView(racersQueueText);
        racersQueueText.getAccessibleContext().setAccessibleName("racersQueueText");
        activityMonitorText.setColumns(20);
        activityMonitorText.setRows(5);
        jScrollPane2.setViewportView(activityMonitorText);
        activityMonitorText.getAccessibleContext().setAccessibleName("activityMonitorText");
        racersQueueLbl.setText("RACER'S QUEUE");
        racersQueueLbl.setToolTipText("");
        activityMonitorLbl.setText("ACTIVITY MONITOR");
        raceTypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Group" }));
        raceTpeLbl.setText("RaceType:");
        startbtn.setText("Start");
        stopBtn.setText("Stop");
        
        addBtn.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
					
				racersQueueText.setText(racersQueueText.getText()+"\n"+addPlayerText.getText());
				addPlayerText.setText("");
			}
		});
        
       
        newRaceBtn.setText("New Race");
        endRace.setText("End Race");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(raceTpeLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(startbtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(addPlayerLbl)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(raceTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addPlayerText, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newRaceBtn)
                                    .addComponent(stopBtn)
                                    .addComponent(endRace))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(addBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activityMonitorLbl)
                        .addGap(97, 97, 97)
                        .addComponent(racersQueueLbl)
                        .addGap(55, 55, 55)))
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPlayerLbl)
                            .addComponent(addPlayerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(racersQueueLbl)
                            .addComponent(activityMonitorLbl))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(raceTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raceTpeLbl))
                        .addGap(18, 18, 18)
                        .addComponent(startbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stopBtn)
                        .addGap(18, 18, 18)
                        .addComponent(newRaceBtn)
                        .addGap(18, 18, 18)
                        .addComponent(endRace)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
     
        pack();
    }// </editor-fold>                        
                                      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChronoTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChronoTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChronoTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChronoTimerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChronoTimerGUI().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel activityMonitorLbl;
    private javax.swing.JTextArea activityMonitorText;
    public javax.swing.JButton addBtn;
    private javax.swing.JLabel addPlayerLbl;
    private javax.swing.JTextField addPlayerText;
    private javax.swing.JButton endRace;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton newRaceBtn;
    private javax.swing.JLabel raceTpeLbl;
    private javax.swing.JComboBox raceTypeCB;
    private javax.swing.JLabel racersQueueLbl;
    private javax.swing.JTextArea racersQueueText;
    private javax.swing.JButton startbtn;
    private javax.swing.JButton stopBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration                   

    

    




}